### PR TITLE
REGISTER.Options.forward_timeout option

### LINKED ISSUE #500: Add `REGISTER.Options.forward_timeout` option
Call timeouts can be executed in three places: the caller, the dealer, or the callee.

In the case of caller-initiated timeouts, there are no extra options added to CALL, and the caller handles the timeout logic itself, sending a CANCEL message if it wants to cancel the call when a timeout occurs.

In the case of dealer or callee-initiated timeouts, a `CALL.Options.timeout` option is added. The spec currently has this to say about which peer handles the timeout:

> The decision by *Dealers* to delegate timeouts to *Callees* supporting this feature MAY be determined by router configuration.

Instead of determining by router configuration (or in addition to the configuration), I propose that an option be added to REGISTER so that a callee may specify its desire to receive the `timeout` option and be responsible for handling timeouts. This would allow the Dealer's timeout forwarding decision to be more granular, that is, on a per-procedure basis (instead of all-or-nothing).

I'd be willing to write the PR for this proposed enhancement, but I first want to make sure the idea is supported.

### PR DESCRIPTION
**Pull request by ecorm**
Fixes #500.
Pinging @Jopie64 who commented in the related issue. Anyone else is welcome to comment/review of course.

### CODE REVIEW

**Comment by ecorm** [comment]
Feel free to bikeshed the `REGISTER.Options.forward_timeout` option name.

**Review by KSDaemon — APPROVED** [review]
👍🏻 I like it

**Review by oberstet — APPROVED** [review]

**Comment by ecorm** [comment]
Sorry, but... bump?

**Comment by KSDaemon** [comment]
Sure! Merging!

**Pull request merged**
