### PR TITLE
Updated META APIs with events payload description

### PR DESCRIPTION
**Pull request by KSDaemon**
Hi! Just added a clear note, that meta events payload consists of positional arguments.

### CODE REVIEW

**Comment by KSDaemon** [comment]
Hi guys! New year holidays are over! :) Ping...

**Comment by oberstet** [comment]
@KSDaemon Hey Konstantin, thx! sorry for sluggish response .. much to do .. exciting times for Crossbar.io (the company) - will disclose more "soon"

**Comment by KSDaemon** [comment]
@oberstet Great to hear! :) btw, don't you think about adding some "long time proved active members" of our community to collaborators list? ;)

**Comment by oberstet** [comment]
@KSDaemon you mean like granting write permissions on this repo? I would do that for you, definitely. let me know ..

**Comment by KSDaemon** [comment]
yep :) That will be great! Mostly on merging such a correction related PRs and also on working with issues.
Thanks!

**Comment by oberstet** [comment]
I'll do that in some minutes .. away for a while! Also, if you have suggestions of who else, I am open!Am 06.02.2018 10:00 vorm. schrieb Konstantin Burkalev <notifications@github.com>:yep :) That will be great! Mostly on merging such a correction related PRs and also on working with issues.
Thanks!

**Comment by KSDaemon** [comment]
Great! 
As i can see, there are few people active for a long time, such as:
* Emile Cormier (@ecorm)
* Andrew Gillis (@gammazero) is very active since he published nexus

**Comment by oberstet** [comment]
alright, added @meejah, @KSDaemon, @ecorm, @mbonneau, @davidwdan to https://github.com/orgs/wamp-proto/teams/project-group for now. rgd Andrew: not sure if I've been in direct touch (if so, no sorry, too much is flowing through my brain).

the idea for adding members is would be: long term contribution to the WAMP protocol specification itself (not "only" implementation) and currently active. if implementation would be the benchmark, we'd had dozens of members - I think this is "fair", as working on the spec itself is work in itself, advancing and increasing the value of WAMP for _all_ implementors and users alike.

let me know if anyone has a different proposal or such! this effort (WAMP) is supposed to be non-discriminatory.

however, that being said, I reserve a role as a "arbiter" ("benevol. dictator", yeah, right;) - I'd say I have done a decent job striking the fine line between keeping everything coherent, and still taking in lots and lots of ideas, suggestions and proposals from many. and keeping the design "coherent" is important - won't give that up ..

further: @all we really should push forward on the RFC. I just don't have the time to give it the love it deserves .. an unlikely will have this year. if anyone is volunteering to do hard work here, you can get your name onto the RFC. depending on amount of work contributed, either in the appendix (contributors .. well, we should list anyone who has contributed anything to the spec / protocol design), or on the main authors list (as a bonus for a lot of work;). I don't have to be (together with Alex) the sole author on the RFC .. 

note: I am sure I overlooked some long term contributors! sorry! gimme a ping if you have a stake in WAMP and are a long term contributor - the repo contributions do not necessarily show this - a lot has happened on the mailing list ..

**Comment by gammazero** [comment]
Have not been in direct contact regarding this, but I am still interested
in contributing to the RFC.  I would at least like to help form and focus
ideas and keep the RFC clean, concise, and purposeful.  Let me know if you
have any specific direction toward RFC.  I can work with others to
coordinate our contributions.  Let me know.

-- Andrew

**Comment by oberstet** [comment]
@gammazero Hi Andrew, nice to meet you=) invitation to join the org sent.

> I would at least like to help form and focus ideas and keep the RFC clean, concise, and purposeful.

I think this would be a very good start: polish up the existing material. straighten out inconsistencies. fill in gaps where implementations / implementors already agreed, yet to be reflected in the spec.

once we have that: there are a couple of areas where users and implementors have asked for multiple times, and we haven't had the time yet to coordinate and hash things out.

Let me list those in an actual (meta) issue .. kinda weird that this important discussion here resides on a merged PR;)

Cheers,
/Tobias

**Comment by KSDaemon** [comment]
Yeah! Filling the gaps... There are still some gaps in spec in different areas. Like wildcard RPC matching... May be we can create a META issue, specially for listing those areas, that need more accurate definition

**Pull request merged**
