### PR TITLE
Add Octamp Client

### PR DESCRIPTION
**Pull request by cydrickn**

### CODE REVIEW

**Comment by KSDaemon** [comment]
Hi @cydrickn Great to have another implementation on board! :)

**Comment by KSDaemon** [comment]
Don't you mind renaming your client while it is not widely used as we already have another called the same `Swamp` swift-based?

**Comment by oberstet** [comment]
oh right, fwiw I agree with @KSDaemon , the name duplication is not ideal, since it will confuse users

unfortunately, the project name and repo https://github.com/cydrickn/swamp-client have "swamp" in it. on the other hand, it's a very new project, so renaming now shouldn't be too bad ..

**Comment by cydrickn** [comment]
sure, let me think for a new name for this, thanks

**Review by oberstet — APPROVED** [review]

**Comment by KSDaemon** [comment]
@cydrickn Thank you! That's great!

**Pull request merged**
