### PR TITLE
Initial event retention draft

### PR DESCRIPTION
**Pull request by hawkowl**
See https://github.com/wamp-proto/wamp-proto/issues/261

cc @oberstet

### CODE REVIEW

**Comment by hawkowl** [comment]
@oberstet I changed it to "Event Retention" as it seems to fit better with the terminology of WAMP, what do you think?

**Comment by oberstet** [comment]
@hawkowl Agreed to both the spec text and the renaming! IMO, this is exactly how this feature should look like.

I will try to raise attention / feedback by posting this on the WAMP mailing list (are you subscribed?): https://groups.google.com/forum/#!forum/wampws

We don't have a formal consensus process for WAMP, but I don't want to just merge it right away either (though I'm completely +1 on this).

**Comment by meejah** [comment]
I think this looks great!

For a concrete use-case, this replaces the pattern of having a "get the state" RPC call paired with an "update the state" PubSub event and collapses it to "publish the state when it changes". It also avoids any question for clients of race-condition type stuff (i.e. do you ask the RPC, and *then* subscribe? if you subscribe and then RPC, what happens if you get a publish before you do the RPC?)

**Comment by ecorm** [comment]
> For a concrete use-case, this replaces the pattern of having a "get the state" RPC call paired with an "update the state" PubSub event and collapses it to "publish the state when it changes".

We are having to do such a get/subscribe pairing in our application. This is a nice, useful feature! :+1:

**Comment by oberstet** [comment]
So we have positive feedback from 3 implementors and no negative feedback. Further, the feature only _adds_ to the AP without changing anything existing (fully optional, fully upwards compat).

Because of above, I am merging=)

**Comment by oberstet** [comment]
@meejah @ecorm yes, this is a nice and common use case! what's also nice: we can add that to WAMP without breaking anything (because, luckily, we've thought about extensibility with WAMP v2 more than with v1;)

**Pull request merged**
