### PR TITLE
Add WAMPex

### PR DESCRIPTION
**Pull request by entone**
Adds WAMPex to the list of client implementations. WAMPex is a pure Elixir implementation of a WAMP client.

### CODE REVIEW

**Comment by oberstet** [comment]
cool! yet another implementation, nice:)

I tried looking a bit at https://gitlab.com/entropealabs/wampex/-/blob/master/priv/client.json .. this is the core of the state machine thing, right? the intro text mentioned it, and it caught my eye .. wondering: is that supposed to be complete rgd initial session establishment .. incl authentication?

> PS: the CI has a fail that is unrelated .. gonna merge this one and fix the issue separately

**Comment by entone** [comment]
It's the "base" of the state machine implementation, other events trigger the state transitions. 

image

it's nice to give a visual representation to the states, and has a nice interface for actually implementing the state machine. There's still quite a bit of code to build out the actual implementation, https://gitlab.com/entropealabs/wampex/-/blob/master/lib/client/session.ex

But the StatesLanguage lib manages all state transitions and ensures you can't get into a bad state. It's also completely asynchronous.

I'm building up a similar library for a router as well.

**Comment by oberstet** [comment]
^ thx for the charts and explanation! looks cool. wondering: it seems the boxes (states?) represent (mostly) WAMP messages while the arrows in between represent messages (received)?

also, not sure you saw this, we have a statechart for session establishment and authentication (but only that .. eg not for all of wamp in general):

https://wamp-proto.org/_static/gen/wamp_latest_ietf.html#rfc.section.7.2.2

**Comment by entone** [comment]
I have seen that.

If you think about the state machine as a graph, specifically a DAG, the
arrows are your edges, and the boxes are your nodes. The edges are some
sort of event that has occurred, in this case, more than likely a message
has arrived over the transport, and causes a state transition aka move to
another box. Once a state has done it's work, usually adding some data to
the internal state of the process, it fires another event(arrow) and we
move to the next state.

Internally we're utilizing an Erlang OTP process called gen_statem, you can
read more about it here, http://erlang.org/doc/design_principles/statem.html

StatesLanguage is a macro that parses the StatesLanguage JSON format, and
creates a gen_statem module that provides callbacks for different
gen_statem callbacks.

I'm the creator of that library as well.

There's some pretty robust docs for the StatesLanguage library at
https://hexdocs.pm/states_language/readme.html

**Pull request merged**
