### PR TITLE
Specify Call Timeouts More Clearly

### LINKED ISSUE #155: Message flow is not specified in Call Timeouts
It's not obvious what the sequence of messages should look like for [Call Timeouts](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#call-timeouts). My guess is that its identical to the sequence shown in [Canceling Calls](https://github.com/tavendo/WAMP/blob/master/spec/advanced.md#canceling-calls), with the exception that the caller does not send a `CANCEL` message. In any case, the intended flow should be made explicit for call timeouts.

### PR DESCRIPTION
**Pull request by ecorm**
Resolves #155

Pinging those who commented in the related issue: @estan @gammazero @oberstet

### CODE REVIEW

**Review by oberstet — APPROVED** [review]

**Comment by ecorm** [comment]
I think this also resolves #265 . Pinging @ericchapman who raised that issue.

**Review by KSDaemon — APPROVED** [review]
I think it is clear! 👍🏻

**Comment by KSDaemon** [comment]
Let's merge? @ecorm

**Comment by oberstet** [comment]
@KSDaemon I've updated the branch to master and merged, as @ecorm is the author and we both reviewed/ack'ed already .. hope this is good for all

**Comment by KSDaemon** [comment]
Absolutely! 👍🏻

**Comment by ecorm** [comment]
Thank you, @oberstet  and @KSDaemon !

**Pull request merged**
