### PR TITLE
SUBSCRIBE and UNSUBSCRIBE's request id sequential

### PR DESCRIPTION
**Pull request by SunFulong**
Other messages' which generate request ID are all using session scope sequential ID, should SUBSCRIBE/UNSUBSCRIBE message using sequential ID too?

### CODE REVIEW

**Comment by SunFulong** [comment]
Additionally, Chapter 2.1.2 lists request ID for these messages using Session Scope IDs.

**Comment by oberstet** [comment]
the spec is correct

**Comment by SunFulong** [comment]
> the spec is correct

Could explain why these messages' request ID need random? and if they are random, they should not list in session scope IDs at chapter 2.1.2.

**Comment by ecorm** [comment]
@SunFulong
I think you are confusing the SUBSCRIBE _request ID_ (which is session scope), with the _subscription ID_ (which is router scope).

**Comment by SunFulong** [comment]
> @SunFulong
> 
> I think you are confusing the SUBSCRIBE _request ID_ (which is session scope), with the _subscription ID_ (which is router scope).

@ecorm 

No, [here](https://wamp-proto.org/wamp_latest_ietf.html#section-2.1.2-11) list SUBSCRIBE.Request is Session Scope ID, but [here](https://wamp-proto.org/wamp_latest_ietf.html#section-5.1.1-3) said its ID must be a random. I think either make the ID sequential, or remove SUBSCRIBE.Request from 2.1.2.

**Comment by ecorm** [comment]
> No, [here](https://wamp-proto.org/wamp_latest_ietf.html#section-2.1.2-11) list SUBSCRIBE.Request is Session Scope ID, but [here](https://wamp-proto.org/wamp_latest_ietf.html#section-5.1.1-3) said its ID must be a random. I think either make the ID sequential, or remove SUBSCRIBE.Request from 2.1.2.

Oh I see now. Yes, it appears the following bullet point in 5.1.1 is in error and contradicts section 2.1.2.

> - Request MUST be a random, ephemeral ID chosen by the Subscriber and used to correlate the Broker's response with the request

The same error appears in [5.1.4](https://wamp-proto.org/wamp_latest_ietf.html#section-5.1.4) for UNSUBSCRIBE.

I'm 99% sure that the request ID in SUBSCRIBE and UNSUBSCRIBE messages is intended to be sequential and Session Scope, and that those were merely copy-paste errors when those sections of the standard were written.

Good catch! :+1:

**Comment by ecorm** [comment]
@oberstet 
> the spec is correct

Sorry, but no, there is a contradiction between sections 2.1.2 / 5.1.1, as well as between 2.1.2 / 5.1.4 as SunFulong has pointed out.

**Comment by KSDaemon** [comment]
I checked wampy, autobahn, nexus. And of course, they all take a sequential next id for these calls.
So let's reopen and merge the fix!

**Comment by SunFulong** [comment]
Thank you, @KSDaemon .

I pushed a bit more modifying to make subscription chapter text like other chapters below.

**Comment by oberstet** [comment]
@SunFulong sorry, seems I've been too quick / didn't read properly;)

**Comment by SunFulong** [comment]
> @SunFulong sorry, seems I've been too quick / didn't read properly;)

English is not my native language, maybe my description is not clear enough, I will try to make the description clearer and more accurate in the future.

**Comment by KSDaemon** [comment]
@SunFulong Don't worry. Most of us are non-native English speakers.

**Pull request merged**
