### PR TITLE
Specification representaion in W3C format (#324)

### PR DESCRIPTION
**Pull request by KSDaemon**
Here it is. Please take a look on spec changes.
Most of things i've done:
* added few blank lines after tables and code blocks
* added `{align="left"}` before every code and table blocks, because i use it as markers to strip away
I hope RFC version does not suffer from this.

### CODE REVIEW

**Comment by KSDaemon** [comment]
Next step will be to setup travis

**Comment by oberstet** [comment]
Cool!! (and sorry for the lag in merging). I'll quickly check if the RFC generation still works;) rgd travis: yeah, this should generated all of the variants (RFC and W3C format), and then publish to our AWS S3 bucket, from where it goes the web via AWS Cloutdfront - this we (crossbar now) use on some of our other repos. we can work on that on a separate follow up issue ..

**Comment by oberstet** [comment]
still works! warnings rgd artwork .. but minor:

```
oberstet@thinkpad-t430s:~/scm/wamp-proto/wamp-proto$ make rfc
mmark -xml2 -page rfc/draft-oberstet-hybi-crossbar-wamp.md > rfc/draft-oberstet-hybi-crossbar-wamp.xml
xml2rfc --text rfc/draft-oberstet-hybi-crossbar-wamp.xml
Parsing file rfc/draft-oberstet-hybi-crossbar-wamp.xml
WARNING: artwork outdented 2 characters to avoid overrunning right margin around input line 1237)
WARNING: artwork outdented 1 characters to avoid overrunning right margin around input line 5909)
Created file rfc/draft-oberstet-hybi-crossbar-wamp.txt
xml2rfc --html rfc/draft-oberstet-hybi-crossbar-wamp.xml
Parsing file rfc/draft-oberstet-hybi-crossbar-wamp.xml
Created file rfc/draft-oberstet-hybi-crossbar-wamp.html
oberstet@thinkpad-t430s:~/scm/wamp-proto/wamp-proto$ git status
Auf Branch master
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

	geändert:       rfc/draft-oberstet-hybi-crossbar-wamp.html
	geändert:       rfc/draft-oberstet-hybi-crossbar-wamp.txt
	geändert:       rfc/draft-oberstet-hybi-crossbar-wamp.xml

```

I commit and push above regenerated RFC text versions.

**Comment by KSDaemon** [comment]
@oberstet @goeddea Ping... Trying to get you here too.... Let's continue this work! :)

**Pull request merged**
