### PR TITLE
Transparent call re-routing

### PR DESCRIPTION
**Pull request by binaek89**
This is the draft sprecification for issue #352 .

In addition to the `wamp.error.unavailable` URI, I added another `wamp.error.no_available_callee` which is the line of communication between the *Dealer*/*Router* to the *Caller* in case all available registrations respond with `wamp.error.unavailable`.

### CODE REVIEW

**Comment by binaek89** [comment]
@oberstet did anyone get a chance to look at the changes?

**Comment by oberstet** [comment]
some quick comments:

* IMO, this feature should be described as part of / additional section to the existing text for shared registrations: https://wamp-proto.org/_static/gen/wamp_latest_ietf.html#shared-registration 
* support (in principle) for this AP feature is optional, hence we need to spec feature announcement (https://wamp-proto.org/_static/gen/wamp_latest_ietf.html#router-role-and-feature-announcement)
* further,  using the feature could require option(s) given by the callee when registering, eg `REGISTER.Options.max_reroutes|int`

eg `max_reroutes == 0` would be the default leading to the existing behavior, while `max_reroutes > 0` would allow to retry on a different callee (than the one that returned `wamp.error.unavailable`) up to the specified maximum number of retries

**Comment by gammazero** [comment]
This looks good.  There is one other failure scenario that maybe the spec should call out how to handle:  When the first _Callee_ returns `wamp.error.unavailable`, and a subsequent _Callee_ returns some other error or fails to respond.  Should the call be re-routed to the next _Callee_, or should the invocation be terminated with the error from the failed _Callee_?

**Comment by binaek89** [comment]
> This looks good. There is one other failure scenario that maybe the spec should be more explicit about: When the first _Callee_ returns `wamp.error.unavailable`, and a subsequent _Callee_ returns some other error or fails to respond. Should the call be re-routed to the next _Callee_, or should the invocation be terminated with the error from the failed _Callee_?
> 
> I think the latter is implied by the text,
> 
> > In case all available registrations of a _Procedure_ responds with a `wamp.error.unavailable` ...
> 
> but asking if anyone else thinks that needs clarification.

The way I see it, any error other than `wamp.error.unavailable` should terminate the invocation (almost as if the re-routing feature does not exist at all)

**Comment by oberstet** [comment]
> The way I see it, any error other than wamp.error.unavailable should terminate the invocation (almost as if the re-routing feature does not exist at all)

yeah, agreed. that would have also been my expectation. the `wamp.error.unavailable` should be reserved as a specific error indicating that no callee could be reached at all while the procedure does exist, so it's different from "no procedure registered, which would only happen when all callees have unregistered)

**Comment by oberstet** [comment]
so I'm +1 on merging, which makes it +3 votes in total. I merge this! should there be more, let's do that on a subsequent PR ..

**Pull request merged**
