### PR TITLE
Elaborate on subsequent progressive invocation options

### LINKED ISSUE #479: Propagation of frozen options in progressive call invocations
According to the recently-added section [Freezing of Options in Progressive Call Invocations](https://wamp-proto.org/wamp_latest_ietf.html#section-11.2-74), the Dealer must apply the options of the initial CALL request to all subsequent INVOCATION messages of the same request. It then gives `disclose_me=true` as an example where all subsequent INVOCATION messages must contain the caller identity.

It also states:

>  Not having to repeat (and not being able to change) options is more in tune with the concept of a media stream where options are set up initially, and the source (Caller) only needs to keep uploading more data thereafter.

So this makes things more efficient for the Caller, but not for the Dealer and Callee which must still communicate these repeated options.

**I'm therefore wondering if the all options (except for `progress`) should be omitted on the Dealer->Callee leg as well in subsequent INVOCATION messages for the sake of efficiency.** This would transfer the burden of remembering the original options to the Callee.

My client implementation (CppWAMP) keeps records of active progressive invocation calls in memory, and it already stores the options of the original CALL.

I believe the only other WAMP implementation currently supporting progressive invocations is the one by @KSDaemon (Wampy.js?)

### PR DESCRIPTION
**Pull request by ecorm**
Fixes #479

### CODE REVIEW

**Comment by ecorm** [comment]
Here is a list of CALL options, for reference:

- `CALL.Options.disclose_me|bool`
- `CALL.Options.ppt_cipher|string`
- `CALL.Options.ppt_keyid|string`
- `CALL.Options.ppt_scheme|string`
- `CALL.Options.ppt_serializer|string`
- `CALL.Options.receive_progress|bool`
- `CALL.Options.rkey`
- `CALL.Options.runmode|string`
- `CALL.Options.timeout|integer`

**Review by oberstet — APPROVED** [review]
I'm +1 on this. It is actually a good restriction, and one that is lenient .. if that's the right word. because of "ignore", not "bail out".

> one minor note: so this "ignore" _any_ option but `progress` applies both to spec defined options _and_ custom options (`x_*`)? fine for me! could be made explicit in the text.

**Comment by ecorm** [comment]
> one minor note: so this "ignore" any option but progress applies both to spec defined options and custom options (x_*)? fine for me! could be made explicit in the text.

Added a sentence to make it explicit for custom options.

**Comment by oberstet** [comment]
so from my side, +1 RTFM .. maybe wait for at least one more vote from an non-author implementor? I'll add the flag.

> sidenote/OT: I'm also going to provide feedback and try a summary of a "step 1" rgd the other issue rgd limit URIs .. not now though ..

**Comment by ecorm** [comment]
> sidenote/OT: I'm also going to provide feedback and try a summary of a "step 1" rgd the other issue rgd limit URIs .. not now though ..

I just wrote a big brain dump regarding the limit URIs issue. I suggest you read it first in case it overlaps with what you have in mind. Or it may trigger some different ideas on your part.

**Comment by oberstet** [comment]
> > sidenote/OT: I'm also going to provide feedback and try a summary of a "step 1" rgd the other issue rgd limit URIs .. not now though ..
> 
> I just wrote a big brain dump regarding the limit URIs issue. I suggest you read it first in case it overlaps with what you have in mind. Or it may trigger some different/better ideas on your part.

thanks a lot! will do.

**Review by KSDaemon — APPROVED** [review]
👍🏻 LGTM!

**Comment by KSDaemon** [comment]
I'm +1 for merging this! 
I'll try to update the Nexus while it is hot)

**Pull request merged**
