### PR TITLE
Add `wamplv` to list of client implementations

### PR DESCRIPTION
**Pull request by samangh**
This pull requests adds [wamplv](https://github.com/samangh/wamplv) to the list of WAMP client applications. This is a WAMP client written in LabVIEW, a data-flow driven language mostly used in the experimental sciences, engineering, robotics and real-time industrial control systems.

It would be great if we could include this in the implementation list, as far as I'm aware there are no other LabVIEW implementations of WAMP.

### CODE REVIEW

**Comment by KSDaemon** [comment]
Wow! That's awesome! I'm wondering, why you haven't come with this PR earlier!

**Review by KSDaemon — APPROVED** [review]
👍🏻

**Comment by oberstet** [comment]
this is pretty cool! and I hope there might be some people get interested in the field of "IoT" and electrical engineering where "Matlab" is a big thing=)

Skimming over the repo, just 2 sidenotes / comments:

* `tcps://loclhost:8080/` as a URL .. the `s` for when running some raw TCP over TLS .. totally makes sense - but will confuse people;) as it is `tls` (or `ssl`) when refering to the raw byte stream without a specific application protocol
* the design of RPCs for integration into Matlab: is the design described somewhere? I only found https://github.com/samangh/wamplv/blob/master/docs/guide.md#asynchronous-calls. Eg it says: "The result of the call will be made available via a user event.". Why? A result and an event are vastly different things .. "normally" .. in WAMP in general. Anyways, I'm just a curious person, and the different ways/flavors of implementing WAMP in vastly different languages/runtimes is a particular interest;)

**Comment by samangh** [comment]
@KSDaemon Thanks for merging this so quickly.

@oberstet Please note that is done LabVIEW, which is quite different to Matlab. They tend to be used in the same work environment (e.g. a physics or electrical laboratory), but are different languages. I've been thinking about making a Matlab client at some point, but I haven’t had the time so far.

With regards to your question, LabVIEW only has a few ways of having asynchronous callbacks and [user events](https://www.ni.com/docs/en-US/bundle/labview/page/creating-custom-events.html) are one of the more commonly used ones. An alternative is [notifiers](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000kFGfSAM&l=en-GB), which my library also fully supports. This way the user has full flexibility in how they integrate the library with the rest of their program.

Sadly there isn't much in the way of textual documentation, that's partially my fault and also due to the graphical nature of LabVIEW.

**Pull request merged**
